### PR TITLE
Update Homebrew commands

### PR DESCRIPTION
**Pull request by ErikMinekus**

### CODE REVIEW

**Comment by fniephaus** [comment]
Thanks, @ErikMinekus! I'm still on vacation but will have a look next week. Sorry for the delay

**Comment by fniephaus** [comment]
The changes look good! But now that Homebrew seems to have merged formulae and casks into one, maybe this workflow should do the same? What do you think, @ErikMinekus?

**Comment by ErikMinekus** [comment]
The brew commands have been merged, but I think Formulae and Casks are still different concepts:

- I would want to know whether I'm installing a CLI tool or an entire app, before installing it.
- Formulae and Casks can have the same name. For example, the `docker` formula is different from the Cask.
- Formulae can be pinned, Casks cannot.
- Casks can be zapped, formulae cannot.

**Comment by fniephaus** [comment]
[`v5.1`](https://github.com/fniephaus/alfred-homebrew/releases/tag/v5.1) is available now!

**Pull request merged**
