### PR TITLE
refactor: Update to python 3 and Alfred 4 and 5

### LINKED ISSUE #52: Not working in Monterey 12.3
Since I have updated to Monterey, I can't get the workflow to work anymore.

This is the error I receive:

`Homebrew & Cask for Alfred[[Script Filter] Queuing argument ''`
`Homebrew & Cask for Alfred[[Script Filter] Script with argv '(null)' finished`
`ERROR: Homebrew & Cask for Alfred[[Script Filter]Code 127: /bin/bash: python: command not found`

### LINKED ISSUE #53: Upgrade to Homebrew python3 version
### Motivation

I had the same problems as anyone after upgrading to Monterey. After a long time of waiting for a solution, unfortunately it seems that the author of the original [alfred-workflow](https://github.com/deanishe/alfred-workflow) library is inactive (his good right to do whatever he wants to do 🙂).

As I was using his workflows a lot, I decided to fork and port his library to python3: [alfred-pyworkflow](https://github.com/harrtho/alfred-pyworkflow). I know the name is not quite creative 😅. In the end the best solution would be that the original author would continue, but until this day I will move on with "my" solution.

The alfred-homebrew workflow also relays on the python2 [alfred-workflow](https://github.com/deanishe/alfred-workflow) and is not working anymore.

### Proposed Solution

I added the [alfred-pyworkflow](https://github.com/harrtho/alfred-pyworkflow) library and refactored the code to use python3 and the library.

In Alfred 5 with the [Gallery](https://alfred.app) beta, the author of Alfred also introduced homebrew as a solution for workflow dependencies. The workflow now will use the location of python3 from ~~the homebrew installation `/usr/local/bin/python3`~~ the system `PATH` via. `/usr/bin/env python3`. The python3 location on ARM Macs is at `/opt/homebrew/bin/python3` https://github.com/Homebrew/discussions/discussions/476#discussioncomment-268372 and not at `/usr/local/bin/python3`. This makes the homebrew install feature of this workflow useless, as it's now a hen / egg problem (needs homebrew to install python3 / needs python3 to install homebrew). I guess for the sake of solution this can be considered as "OK" for now an can be cleaned-up late.

Please take a look at the solution (if you find the time review the changes critical, as we both would benefit from it)

And when I'm already here: Thank you for your alfred-homebrew workflow!

### PR DESCRIPTION
**Pull request by harrtho**
Resolves #53
Resolves #52

### CODE REVIEW

**Comment by fniephaus** [comment]
Hi @harrtho, thanks for the PR! I don't have access to a machine running Monterey at the moment, but I will take a look in the next two weeks. If anyone can give this a try, that'd be great too.

Cheers,
Fabio

**Comment by nhat** [comment]
Thanks @harrtho! Works fine for me on an M1 MBP.

I stopped using this workflow after switching to a M1 Mac and just discovered your PR now.

**Comment by jim465** [comment]
Also tested on M1Pro and it works.
Thanks!

**Comment by brandonwie** [comment]
Tested on M2 Pro and it works well. Thanks.

**Comment by fniephaus** [comment]
Thanks again for the contribution and apologies for the delay. I've merged this and pushed a new [v6.0](https://github.com/fniephaus/alfred-homebrew/releases/tag/v6.0). :)

**Pull request merged**
